"""Test one-hot CTNA against R ground truth (1000 configs)."""

import json
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from tna.prepare import import_onehot
from tna.model import ctna

# Load ground truth generated by R TNA 1.2.0
_DATA_PATH = Path(__file__).parent / "data" / "onehot_ctna_groundtruth.json"
with open(_DATA_PATH) as f:
    CONFIGS = json.load(f)


def _config_id(cfg: dict) -> str:
    p = cfg["params"]
    return (
        f"seed{p['seed']}_{p['n_cols']}cols_ws{p['window_size']}"
        f"_{p['window_type']}_agg{p['aggregate']}"
    )


@pytest.mark.parametrize("cfg", CONFIGS, ids=_config_id)
def test_ctna_matches_r(cfg: dict) -> None:
    """Verify CTNA weights, inits, and labels match R ground truth."""
    p = cfg["params"]

    # Reconstruct DataFrame from raw_data
    df = pd.DataFrame(cfg["raw_data"])
    actor_arg = "Actor" if p["n_actors"] > 1 else None
    session_arg = "Session" if p["n_sessions"] > 1 else None

    seqs = import_onehot(
        df,
        cols=p["cols"],
        actor=actor_arg,
        session=session_arg,
        window_size=p["window_size"],
        window_type=p["window_type"],
        aggregate=p["aggregate"],
    )

    m = ctna(seqs)

    # R's auto_unbox may turn single-element vectors into scalars
    labels = cfg["ctna_labels"]
    if isinstance(labels, str):
        labels = [labels]
    weights_flat = cfg["ctna_weights"]
    if isinstance(weights_flat, (int, float)):
        weights_flat = [weights_flat]
    inits_raw = cfg["ctna_inits"]
    if not isinstance(inits_raw, list):
        inits_raw = [inits_raw]

    # Check labels
    assert m.labels == labels, (
        f"Labels mismatch: got {m.labels}, expected {labels}"
    )

    # Check weights
    n = len(labels)
    expected_weights = np.array(weights_flat).reshape(n, n)
    np.testing.assert_array_almost_equal(
        m.weights, expected_weights, decimal=10,
        err_msg="Weights mismatch",
    )

    # Check inits (R produces NaN when first column is all-NA)
    expected_inits = np.array(
        [x if x is not None else np.nan for x in inits_raw]
    )
    np.testing.assert_array_almost_equal(
        m.inits, expected_inits, decimal=10,
        err_msg="Inits mismatch",
    )
